################################################################################
#
#  Copyright (C) 2023 retro.ai
#  This file is part of retro-dapp - https://github.com/RetroAI/retro-dapp
#
#  SPDX-License-Identifier: Apache-2.0
#  See the file LICENSE for more information.
#
################################################################################

name: Build CI
on:
  push:
    paths:
      - 'lib/**'
      - 'tools/**'
  pull_request:
    paths:
      - 'lib/**'
      - 'tools/**'
  schedule:
    - cron: '0 0 * * 0'

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Don't run on schedule unless this is the main branch
    if: (github.event_name != 'schedule' || (github.event_name == 'schedule' && github.ref == 'refs/heads/main'))

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04

          # TODO: Update OpenCV to build on Ubuntu 22.04
          #
          # Current error is:
          #
          #   [ 96%] Generating ../../bin/opencv.js
          #   TypeError: a bytes-like object is required, not 'str'
          #
          #- os: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the
    # job
    steps:
      - name: Build environment information
        run: 'echo "Matrix OS: ${{ matrix.os }} on $HOSTNAME with $(getconf _NPROCESSORS_ONLN) cores"'

      - name: Set git credentials
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "retro.gaming.ai@gmail.com"

        # Check-out the repository under $GITHUB_WORKSPACE, so the job can
        # access it
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Restore dependency build files
        id: restore-depends
        uses: actions/cache@v3
        with:
          path: |
            frontend/src/generated
            tools/dist
            tools/repos/emsdk
          key: restore-depends-${{ matrix.os }}-${{ hashFiles('tools/depends/native/emscripten/*', 'tools/depends/wasm/ade/*', 'tools/depends/wasm/codecbox.js/*', 'tools/depends/wasm/ffmpeg/*', 'tools/depends/wasm/libvpx/*', 'tools/depends/wasm/opencv/*', 'tools/depends/wasm/x264/*') }}

      - name: Build depends
        if: steps.restore-depends.outputs.cache-hit != 'true'
        run: tools/build-depends.sh all

      - name: Build libraries
        run: lib/build-ci.sh
