# .github/workflows/clang-format-check.yml
name: Clang Format Check

on:
  push:
    paths:
    - 'lib/**.cpp'
    - 'lib/**.h'
    - '.clang-format'
  pull_request:
    paths:
    - 'lib/**.cpp'
    - 'lib/**.h'
    - '.clang-format'

jobs:
  format:
    name: Clang Format
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Clang Format
      run: sudo apt-get install -y clang-format-15

    - name: Run Clang Format
      run: |
        find lib -regex '.*\.\(cpp\|hpp\|h\|cc\|cxx\)' -exec clang-format-15 -style=file -i {} \;
        git diff --exit-code --color
